name = "asympt"
version = "0.1.0"
defaultTargets = ["asympt"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[lean_lib]]
name = "Asympt"

[[lean_exe]]
name = "asympt"
root = "Main"
